# Generated by Django 4.0 on 2021-12-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="seald_id",
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
