# Generated by Django 4.0 on 2021-12-09 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_user_seald_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="upload",
            name="uploader_email",
        ),
    ]
