# Generated by Django 4.0 on 2021-12-09 20:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_upload_uploader_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="session",
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name="upload",
            name="seald_message_id",
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
