# Generated by Django 4.0 on 2021-12-10 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_upload_session_alter_upload_seald_message_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="upload",
            name="seald_message_id",
        ),
    ]
